version: '3'
services:
  redis:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./redis
    networks:
      - backend
  server:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    ports:
      - '80:80'
    networks:
      - frontend
  home:
    stdin_open: true
    restart: always
    depends_on:
      - server
    build:
      dockerfile: Dockerfile.dev
      context: ./home
    environment:
      - PORT=3000
      - NODE_OPTIONS=--openssl-legacy-provider
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ./home:/app
    networks:
      - frontend
  documentation:
    stdin_open: true
    restart: always
    depends_on:
      - server
    build:
      dockerfile: Dockerfile.dev
      context: ./documentation
    environment:
      - PORT=4000
      - NODE_OPTIONS=--openssl-legacy-provider
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ./documentation:/app
    networks:
      - frontend
  calculator:
    stdin_open: true
    restart: always
    depends_on:
      - redis
      - server
      - api
    build:
      dockerfile: Dockerfile.dev
      context: ./calculator
    environment:
      - PORT=5000
      - NODE_OPTIONS=--openssl-legacy-provider
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - /app/node_modules
      - ./calculator:/app
    networks:
      - frontend
      - backend
  api:
    stdin_open: true
    restart: always
    depends_on:
      - redis
    build:
      dockerfile: Dockerfile.dev
      context: ./api
    environment:
      - PORT=3124
      - NODE_OPTIONS=--openssl-legacy-provider
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
    volumes:
      - /app/node_modules
      - ./api:/app
    networks:
      - frontend
      - backend
networks:
    backend:
    frontend: