version: '3'
services:
  redis:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./redis
    ports:
      - '127.0.0.1:6379:6379'
    networks:
      - backend
  # server:
  #   restart: always
  #   build:
  #     dockerfile: Dockerfile.dev
  #     context: ./server
  #   ports:
  #     - '127.0.0.1:8080:80'
networks:
    backend:
    frontend: